name: Deploy Django

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Secrets
        run: |
          if [ -z "${{ secrets.RSA_PRIVATE }}" ]; then
            echo "RSA_PRIVATE is not set."
            exit 1
          else
            echo "RSA_PRIVATE is set."
          fi

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.RSA_PRIVATE }}

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_HOSTNAME }}" >> ~/.ssh/known_hosts

      - name: Deploy with Docker Compose
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_HOST "cd /path/to/your/project && docker compose pull && docker compose up -d"
